// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xagojidwrenkgtjkbamq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhZ29qaWR3cmVua2d0amtiYW1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MjA0ODYsImV4cCI6MjA3MjQ5NjQ4Nn0.FyVk4vPQyEEOt-ceQGM7BZb1WL-3w_SwVB4nWmKVgdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});